/*global casper*/
/*jshint strict:false*/
// Generated by CoffeeScript 1.4.0
(function() {
  "A small subset of the run.js written in coffeescript";

  var steps;

  steps = 0;

  casper.options.onStepComplete = function() {
    return steps++;
  };

  casper.test.begin("writing async tests in coffeescript", 4, function(test) {
    casper.start("tests/site/index.html", function() {
      test.assertTitle("CasperJS test index", "Casper.start() casper can start itself an open an url");
      test.assertEquals(this.fetchText("ul li"), "onetwothree", "Casper.fetchText() can retrieves text contents");
      return this.click("a[href=\"test.html\"]");
    });
    casper.then(function() {
      test.assertTitle("CasperJS test target", "Casper.click() casper can click on a text link");
      return this.click("a[href=\"form.html\"]");
    });
    return casper.run(function() {
      test.assertEquals(steps, 3, "Casper.options.onStepComplete() is called on step complete");
      this.options.onStepComplete = null;
      return this.test.done();
    });
  });

}).call(this);
